### ISSUE TITLE
  Regarding the issue of modifying the input quantity。

### ISSUE THREAD

**Issue by zyg234** [linClubs/BEVFusion-ROS-TensorRT#1]
Q1：Bevfusion_ At the end of ros.cpp: cv:: Mat img=cv:: imread (pkg_path+"/configurations/cuda bevfusion. jpg"). c_ Str()

What is the purpose of loading this image。

Q2：What changes should I make if I want to input only one camera (front camera)。

Looking forward to your reply very much！

**Comment by linClubs** [comment]
Due to the author's limited abilities and the need to quickly publish images with ros， just do it.

You can improve this processing method if it's convenient for you, thanks. ^_^

**Comment by linClubs** [comment]
It is recommended not to use BEV method with single image, but yolo-xxx.

**Comment by zyg234** [comment]
Thank you very much for your reply and suggtions. If I have any improvements, I will let you know.

**Comment by zyg234** [comment]
Thank you very much for your reply and suggestions. If I have any improvements, I will let you know.
