### ISSUE TITLE
how to get camera_intrinsics.tensor and camera2lidar.tensor by my own sensor layout

### ISSUE THREAD

**Issue by generalchan825** [linClubs/BEVFusion-ROS-TensorRT#21]
@linClubs hi bro, may I ask how to get the camera_intrinsics.tensor and camera2lidar.tensor when using my own sensor layout? Thanks a lot for your response!
![image](https://github.com/user-attachments/assets/0e7b9c17-f1ee-4d0f-9308-90b1f5098b34)

**Comment by linClubs** [comment]
you need to caliberate your sensor. you can refer to [link](https://github.com/linClubs/Calibration-Is-All-You-Need).
