### ISSUE TITLE
opencv报错

### ISSUE THREAD

**Issue by leizi111** [linClubs/BEVFusion-ROS-TensorRT#23]
你好，我在播包后opencv就会抛异常，想请教一下这个问题改如何解决
```
terminate called after throwing an instance of 'cv::Exception'
what(): OpenCV(4.5.4) ../modules/imgproc/src/resize.cpp:4045: error: (-215:Assertion failed) !ssize.empty() in function 'resize'
```

**Comment by leizi111** [comment]
> 你好，我在播包后opencv就会抛异常，想请教一下这个问题改如何解决
> 
> ```
> terminate called after throwing an instance of 'cv::Exception'
> what(): OpenCV(4.5.4) ../modules/imgproc/src/resize.cpp:4045: error: (-215:Assertion failed) !ssize.empty() in function 'resize'
>  ```
解决了，注释掉bevfusion_ros.cpp的第86行cv::resize(img, img, cv::Size(img.size().width /2, img.size().height /2))就能正常运行了

**Comment by linClubs** [comment]
是不是还没读到图形，img为空，得做限制，我测试程序是在opencv4.2上测试的

**Comment by linClubs** [comment]
> > 你好，我在播包后opencv就会抛异常，想请教一下这个问题改如何解决
> > ```
> > terminate called after throwing an instance of 'cv::Exception'
> > what(): OpenCV(4.5.4) ../modules/imgproc/src/resize.cpp:4045: error: (-215:Assertion failed) !ssize.empty() in function 'resize'
> > ```
> 
> 解决了，注释掉bevfusion_ros.cpp的第86行cv::resize(img, img, cv::Size(img.size().width /2, img.size().height /2))就能正常运行了

好的
